### ISSUE TITLE
work on forntend

### ISSUE THREAD

**Issue by sonalkr132** [NIT-dgp/cat-forum#1]
Use bootstarp for front end design and make sure it's responsive.

**Comment by ananyo2012** [comment]
These are the design issues left as of now
- [x] Modify header and footer of application
- [x] Modify design of Login/Signup Page
- [x] Modify design of How to ask and Badges page. Make them visible even when not logged in
- [x] Modify design of activity page
- [x] Modify design of post page
- [x] Modify design of Admin login page
- [x] Modify thread box and remove pagination from home page
- [x] Modify design of thread show page
- [x] Modify design of search page
- [x] Adjust Upvote, downvote and comment icons
- [x] Modify design of Profile page
- [x] Modify design of Admin Flags page

**Comment by ghoshbishakh** [comment]
@ananyo2012 is it hosted somewhere? so that I can check the current version?

**Comment by ananyo2012** [comment]
Yes there is a version till the current master. Here is the link: http://catforum-ananyo.rhcloud.com/

**Comment by ananyo2012** [comment]
I will work on the remaining design changes soon.

**Comment by ananyo2012** [comment]
@sonalkr132 Work on forntend is complete now. This is the summary of the frontend redesign
1. A complete bootstrap based UI
2. Fontawesome for glyphicons and commonly used icons
3. An infinitescrolling threads page with threads organised in blocks
4. Thread blocks fit optimally leaving least space done with [masonry](http://masonry.desandro.com/)

**Comment by ananyo2012** [comment]
Closing this one. Open new issues for any design related fixes.
