### ISSUE TITLE
long thread descriptions are a design issue

### ISSUE THREAD

**Issue by ghoshbishakh** [NIT-dgp/cat-forum#10]
New Threads page lists the threads with title and description. However if the description is lengthy still then it is displayed fully. This is creatig a design issue. Somehow the text must be cropped after a certain max length.

**Comment by sonalkr132** [comment]
you might find [truncate](http://apidock.com/rails/ActionView/Helpers/TextHelper/truncate) useful

**Comment by ghoshbishakh** [comment]
Whithout truncating the body I can arrange the posts in a massonary style. But still a limit is necessary I guess.

![screenshot from 2015-06-13 22-46-48](https://cloud.githubusercontent.com/assets/5156787/8145256/44539502-121e-11e5-9873-3730fbf186bb.png)
![screenshot from 2015-06-13 22-46-59](https://cloud.githubusercontent.com/assets/5156787/8145255/444b7e62-121e-11e5-9ce2-47774d6283f0.png)
![screenshot from 2015-06-13 22-47-08](https://cloud.githubusercontent.com/assets/5156787/8145257/44567ee8-121e-11e5-8a02-6d0dd3ffd819.png)

**Comment by sonalkr132** [comment]
If you don't want to truncate then you can use something like http://masonry.desandro.com/.

Nav bar looks nice :wink:

**Comment by ghoshbishakh** [comment]
yes I am already using it.

**Comment by sonalkr132** [comment]
I particularly like this one http://tympanus.net/Development/GridLoadingEffects/index2.html
