### ISSUE TITLE
design iterations

### ISSUE THREAD

**Issue by ghoshbishakh** [NIT-dgp/cat-forum#11]
I will keep posting most changes. Keep your valuable comments flowing everyone.

**Comment by ghoshbishakh** [comment]
![screenshot from 2015-06-13 23-01-36](https://cloud.githubusercontent.com/assets/5156787/8145305/62e1dff4-1220-11e5-8068-4e7eb246a4ef.png)

**Comment by sonalkr132** [comment]
Please make a pull request with your work as well. It doesn't have to be final or perfect, we will mark it in progress.

**Comment by ghoshbishakh** [comment]
i have deleted all the css files and recreating the layouts.. so figuring out a proper pull request? i dont know how to proceed.

**Comment by sonalkr132** [comment]
You can make a commit where you have cleaned all the styles and then add more commits as go on adding features. For ex: point where you have your nav bar working can be one commit.
Also, I hope you know that once you make a PR, it is not locked. You can keep pushing commits to same branch and your PR will be updated accordingly.

**Comment by ghoshbishakh** [comment]
ok then.. I'll be sending PRs..

**Comment by ghoshbishakh** [comment]
actually trying to give it a material look.. 
![screenshot from 2015-06-14 00-24-36](https://cloud.githubusercontent.com/assets/5156787/8145609/c73d07ca-122b-11e5-8676-637726e6c4e9.png)

**Comment by sonalkr132** [comment]
Hi It is looking nice. I hope you will be able to figure out where you are going to put rest of things(like, dislike, flag, no of answers and time)

**Comment by ghoshbishakh** [comment]
![screenshot from 2015-06-14 13-33-50](https://cloud.githubusercontent.com/assets/5156787/8147778/0edaef02-129a-11e5-8ab1-8b9bc1c5b57b.png)

**Comment by sonalkr132** [comment]
It looks nice! Can you do something about "new thread"? It seems kinda out of place and lonely. Or is it just because it is screenshot?

**Comment by ghoshbishakh** [comment]
yes ofcourse.. I will come to it later.

**Comment by ghoshbishakh** [comment]
i have noticed some problems with the like / dislike buttons and their ajax updation. When I click it, a new set of div is created inside the original one. Trying to fix it or atleast put a rough patch.

**Comment by sonalkr132** [comment]
I hope you have figured out how ajax is working?
ajax call -> create action of like_count_controller.rb -> gives js response and renders create.js.erb -> replaces html of appropriate div with partial _new_thread.html.erb

**Comment by ghoshbishakh** [comment]
ok... I am trying to figure out those.

**Comment by ghoshbishakh** [comment]
New thread button
![screenshot from 2015-06-14 15-33-09](https://cloud.githubusercontent.com/assets/5156787/8148131/b8f6f912-12aa-11e5-8ee1-fbf4c641ff20.png)

**Comment by ghoshbishakh** [comment]
I think it would be better if you create a separate branch for design overhaul iterations and i will send PRs to them @sonalkr132

**Comment by sonalkr132** [comment]
Thats not necessary, you can send PR to github_master. I wont merge it until you have finished something which can be merged.

**Comment by ghoshbishakh** [comment]
![screenshot from 2015-06-20 13-23-10](https://cloud.githubusercontent.com/assets/5156787/8266515/9b6527ee-174f-11e5-85ba-5408e2727aab.png)

**Comment by ghoshbishakh** [comment]
hosted at http://catforum.herokuapp.com/
@ananyo2012 
@sonalkr132
please test the threadlist and thread show pages.

**Comment by sonalkr132** [comment]
It look great @ghoshbishakh. There are few thing minor things which we might need to revisit/add but it is totally perfect for now.

**Comment by ghoshbishakh** [comment]
yes many many small changes are left. Just feedback for the overall design and layout

**Comment by sonalkr132** [comment]
I think we should add a progress bar. I could never tell if the website accepted my request when I clicked on button. Possibly it will also help with design being too _bald_ 
There are quite a few options available. Here.. I will get your started https://github.com/caarlos0/nprogress-rails

**Comment by ghoshbishakh** [comment]
yes i noticed that. May be youtube style loading indicator?

**Comment by sonalkr132** [comment]
nprogress-rails will achieve the same thing as youtube style loading indicator. 
Among the minor adjustments: 
![screenshot from 2015-06-22 13 08 17](https://cloud.githubusercontent.com/assets/7680662/8277401/1947caa4-18e0-11e5-9ad9-dc7f58e0111b.png)
Please add some left and right margin to flash messages.

**Comment by sonalkr132** [comment]
If you want some real design perspective, message Ani bhiya with link and ask him for feedback.

It looks nice or not is possibly only feedback I can give you.

**Comment by ananyo2012** [comment]
@ghoshbishakh i don't see the SEO changes.didn't you update your branch before starting your work?

**Comment by ghoshbishakh** [comment]
actually no. It is older one. I will incorperate them before sending PR

**Comment by ghoshbishakh** [comment]
![screenshot from 2015-06-23 16-25-04](https://cloud.githubusercontent.com/assets/5156787/8304541/8650d4d0-19c4-11e5-8fb5-fc5dc61c054e.png)

check heroku

**Comment by sonalkr132** [comment]
Sorry, I checked it but forgot to reply. It looks nice.
Good work on status bar!
I think it will look better if you use some darker shade for it tho, may be one which have used for border-bottom #00796B

**Comment by ghoshbishakh** [comment]
by status bar which part do you mean? footer?

**Comment by sonalkr132** [comment]
No the youtube thingy we were talking about, the one which shows what is the status of request being processed.

**Comment by ghoshbishakh** [comment]
ok.. will change the color

**Comment by ananyo2012** [comment]
@ghoshbishakh there are some inline css in the search button.can you put them on the stylesheet?

**Comment by ghoshbishakh** [comment]
i cant see any @ananyo2012 
only the button has one display none property
and those come from a partial that ill have to see then

**Comment by ananyo2012** [comment]
yeah i am talking about that.there's only one.it is in
new_threads/_search.html.erb.try putting it in the stylesheet.it adds to
seo optimizations.

**Comment by ananyo2012** [comment]
Closing this one too in league with #1
