### ISSUE TITLE
In place edits not working

### ISSUE THREAD

**Issue by ananyo2012** [NIT-dgp/cat-forum#22]
When I try to edit the description and title of the thread it doesn't work. Though it works just after the thread creation but it doesn't work after that.

**Comment by sonalkr132** [comment]
Probably it would good idea to remove it entirely. It creates lot of styling issue as well.
May a be an edit button with some javascript to show edit template.

**Comment by sonalkr132** [comment]
Not to mention it has always been buggy.

**Comment by ananyo2012** [comment]
Yes we can use JavaScript for in place editing.
