### ISSUE TITLE
Home page asks "Not a member yet?" even when user is signed in (logged in).

### ISSUE THREAD

**Issue by ghoshbishakh** [NIT-dgp/cat-forum#4]
When a user is logged in the message "Welcome to our CAT Forum! Not a member yet? Why don't you click on sign up, it will only take a few minutes. You can log in with Facebook too. Browse through the our list of recent threads, We are sure you will find something interesting. " should not be displayed I think.

**Comment by sonalkr132** [comment]
Thats right. It should not show up when user is logged in.

**Comment by ghoshbishakh** [comment]
I have just fixed that. So should I send a pull request for these 2 lines only?

**Comment by sonalkr132** [comment]
yeah sure. Pull requests are suppose to fix one issue at a time. Make sure you amend your commit message to include the issue number.

**Comment by ghoshbishakh** [comment]
any more changes before merging?

**Comment by sonalkr132** [comment]
yes. Read [this](http://chris.beams.io/posts/git-commit/) and fix your [commit](https://github.com/ghoshbishakh/cat-forum/commit/bb508474e9023a4365b7093a6d1a01551f1f945d) message

**Comment by ghoshbishakh** [comment]
how can i solve the conflicts ?? any guide ? I am finding it confusing.

**Comment by sonalkr132** [comment]
I found [this](http://www.lynda.com/Git-tutorials/Git-Essential-Training/100222-2.html) lynda tut very useful when I was getting started. If you could watch it then you must.

A very important resource for any of your git related problem is [pro git book](https://git-scm.com/book/en/v2). [Here](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging) is the section where they explain the basics.

Git is something you will eventually HAVE to learn. So don't consider it added chore.

**Comment by ghoshbishakh** [comment]
yes ofcourse. I was wondering what is the proper workflow. Making the ruby project run itself makes varous changes to various files. So how to commit only the changes that are required and then how to merge changes like complete reindintation and all that changes the files completely. Anyway thanks. Will read the book.
