### ISSUE TITLE
Deciding proper way of including bootstrap

### ISSUE THREAD

**Issue by ghoshbishakh** [NIT-dgp/cat-forum#6]
Which will be the proper way of using bootstrap with rails so that it can be deployed easily also?
Method 1: Including the brecompiled .css and .js files as explained in http://stackoverflow.com/questions/18371318/installing-bootstrap-3-on-rails-app

Method 2:  By adding the bootstrap-sass gem as explained here: https://github.com/twbs/bootstrap-sass#a-ruby-on-rails

**Comment by sonalkr132** [comment]
Depends on how you plan on using it. If you won't be using much of features from bootstrap, then you can delete unnecessary things from precompiled assets and make the js and css files lighter (faster website). However I don't think you would be willing go through that much of pain for such small gain, so just install the gem.

Check this out: http://railscasts.com/episodes/328-twitter-bootstrap-basics?view=asciicast

**Comment by poluruprvn** [comment]
Or we can use https://github.com/purifycss/purifycss to remove unused css.

**Comment by ananyo2012** [comment]
Using [bootstrap-sass](https://github.com/twbs/bootstrap-sass) gem. Closing this one.
