### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by sonalkr132** [NIT-dgp/cat-forum#8]
We don't any authorization in our app. I would suggest that you use [cancancan](https://github.com/CanCanCommunity/cancancan). 

Watch [this](http://railscasts.com/episodes/192-authorization-with-cancan) or go through [my app](https://github.com/glittergallery/GlitterGallery).

We also need to write tests for this.

**Comment by ananyo2012** [comment]
ok i will be doing it

**Comment by sonalkr132** [comment]
Closed by #15
