### ISSUE TITLE
bundle update fails.

### ISSUE THREAD

**Issue by ghoshbishakh** [NIT-dgp/cat-forum#9]
![screenshot from 2015-06-13 14-24-43](https://cloud.githubusercontent.com/assets/5156787/8143719/f9f11f52-11d7-11e5-9a21-0ac5a1facf52.png)

**Comment by sonalkr132** [comment]
Why are you trying bundle update anyway?

**Comment by ghoshbishakh** [comment]
I was looking at some material design css frameworks. One of them required
latest sass.

**Comment by sonalkr132** [comment]
Please don't do a complete bundle update of all the gems, just update the sass gem.

**Comment by ghoshbishakh** [comment]
okey..
